config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ingredients, only: [:index, :show]
  resources :months, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calander.rb
class Calander < ApplicationRecord
  belongs_to :ingredient
  belongs_to :month
end

app/models/category.rb
class Category < ApplicationRecord
  include PgSearch::Model
  has_many :ingredients

  multisearchable against: :name
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  include PgSearch::Model
  belongs_to :category
  has_many :calanders
  has_many :months, through: :calanders

  multisearchable against: :name
end

app/models/month.rb
class Month < ApplicationRecord
  include PgSearch::Model
  has_many :calanders
  has_many :ingredients, through: :calanders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: []
end

app/controllers/calander_controller.rb
class CalanderController < ApplicationController
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @months = Month.all
    @categories = Category.all
    if params[:query].present?
      @ingredients = PgSearch.multisearch(params[:query])
    else
      @ingredients = Ingredient.all
    end
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    @category = @ingredient.category
  end

  private

  def strong_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def index
    @months = Month.all
  end

  def show
    @month = Month.find(params[:id])
    @categories = Category.all
  end

  private

  def strong_params
    params.require(:month).permit(:name, :season)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @month = Month.find_by(name: Date.today.strftime('%B'))
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/index.html.erb
<div class="page_container" id='homepage'>
  <span class="search_banner">
    <%= form_tag ingredients_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for an Ingredient."
      %>
      <%= submit_tag "Search", class: "btn" %>
    <% end %>
    <%= link_to 'Reset Calander', ingredients_path, class: 'btn reset' %>
  </span>
  <div class="container">
    <span class="category-search">
      <% @categories.each do |category| %>
        <button class="category" data-category="<%= category.name %>">
          <%= category.name %>
        </button>
      <% end %>
    </span>
    <div class="calander-table">
      <% @months.each do |month| %>
        <div class="card">
          <h1 class="month-name"><%= link_to month.name, month_path(month) %></h1>
          <h4><%= month.season %></h4>
          <span class='ingredient_selection'>
            <%# selected_ten = @ingredients.sample(20) %>
            <% @ingredients.each do |ingredient| %>
              <% if params[:query].present? %>
                <% ingredient.searchable.month_ids.each do |id| %>
                  <% if id == month.id %>
                    <div class="ingredient" data-category="<%= ingredient.searchable.category.name %>">
                      <%= ingredient.searchable.name %>
                    </div>
                  <% end %>
                <% end %>
              <% else %>
                <% ingredient.month_ids.each do |id| %>
                  <% if id == month.id %>
                    <div class="ingredient" data-category="<%= ingredient.category.name %>">
                      <%= ingredient.name %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<div>
  <h3 class="month-name"><%= @ingredient.name %></h3>
</div>
<div class="container">
  <div class="content">
    <div class="category">
      <h4><%= @category.name %></h4>
      <% @category.ingredients.sample(5).each do |ingredient| %>
        <div class="ingredient" data-category="<%= ingredient.category.name %>">
          <%= ingredient.name %>
        </div>
      <% end %>
    </div>
    <div class="recipes">

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeasonalityCalanderApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/months/show.html.erb
<div class="container">
  <div>
    <h3 class="month-name"><%= @month.name %></h3>
  </div>
  <div class="calander-table">
    <% @categories.each do |category| %>
      <div class="card" id='homepage-card'>
        <div class="image">
          <h3 class='home-category-name'><%= category.name %></h3>
          <% category.name == 'Fish & Shellfish' ? source = ('Fish')  : source = (category.name) %>
          <%= image_tag "https://res.cloudinary.com/dqu728tid/image/upload/v1621102820/#{source}.jpg", crop: :fit %>
        </div>
        <span class="ingredient_selection">
          <% category.ingredients.each do |ingredient| %>
            <% if ingredient.month_ids.any?(@month.id) %>
              <div class="ingredient ingredient-search" data-category="<%= category.name %>">
                <%= ingredient.name %>
                <%#= link_to ingredient.name, ingredient_path(ingredient), class: 'ingredient-show-link' %>
              </div>
            <% end %>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<span class="homepage_banner show">
  <h1 class='app-name'>Seasonality Calander</h1>
  <div class="text">
    <p>
      Welcome to my version of Scot Food & Drinks Seasonality Calander.
      This is my take on their PDF version showing whats in sesosn for each month, separted out by categories.
    </p>
  </div>
  <%= link_to 'Full Calander', ingredients_path, class:'ingredient-link' %>
</span>
<div class="calander-table">
  <% @categories.each do |category| %>
    <div class="card" id='homepage-card'>
      <div class="image">
        <h3 class='home-category-name'><%= category.name %></h3>
        <% category.name == 'Fish & Shellfish' ? source = ('Fish')  : source = (category.name) %>
        <%= image_tag "https://res.cloudinary.com/dqu728tid/image/upload/v1621102820/#{source}.jpg", crop: :fit %>
      </div>
      <span class="ingredient_selection">
        <% category.ingredients.each do |ingredient| %>
          <% if ingredient.month_ids.any?(@month.id) %>
            <div class="ingredient ingredient-search" data-category="<%= category.name %>">
              <%= link_to ingredient.name, ingredient_path(ingredient), class: 'ingredient-show-link' %>
            </div>
          <% end %>
        <% end %>
      </span>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if !current_page?(root_path) %>
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Homepage</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/ingredients">Full Calander</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% end %>